apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: your-application-name
spec:
  project: default
  source:
    repoURL: https://github.com/koushikpr/Ruby-On-rails-automation-using-ArgoCD-Tekton.git
    path: kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: default
