apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - command:
        - bundle
        - exec
        - rails
        - s
        - -p
        - "3000"
        - -b
        - 0.0.0.0
        image: 030902/ruby:latest
        name: backend
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /myapp/backend
          name: backend-storage
      volumes:
      - name: backend-storage
        persistentVolumeClaim:
          claimName: backend-pvc
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
